# Generated by Django 5.0.7 on 2024-08-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=255)),
                ('result', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
